server:
  port: 8080

endpoints:
  actuator:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/deposit?useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
  thrift:
    server:
      service-id: deposit-thrift-service
      service-model: hsHa
      port: 25000
      worker-queue-capacity: 1000
      hs-ha:
        min-worker-threads: 5
        max-worker-threads: 20
        keep-alived-time: 3

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.icekredit.rpc.thrift.examples.http.entities