server:
  port: 8080

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        register-health-check: true
        health-check-interval: 10s
        tags:
          - calculator-8080
          - http
        health-check-path: /health
        service-name: thrift-calculator-rest-server
        instance-id: ${spring.cloud.consul.discovery.service-name}:${spring.cloud.client.ipAddress}:${server.port}
        prefer-ip-address: true
  thrift:
    server:
      service-id: thrift-calculator-rpc-server
      service-model: hsHa
      port: 25000
      worker-queue-capacity: 1000
      hs-ha:
        min-worker-threads: 5
        max-worker-threads: 20
        keep-alived-time: 5
      discovery:
        enabled: true
        host: localhost
        port: 8500
        tags:
          - hsHa
          - calculator-25000
        health-check:
          enabled: true
          check-interval: 10
          check-timeout: 3
